// This file is generated by Vagebond\Runtype
// App\Http\Resources\RecipeResource
export type RecipeResourceType = {
    id: string;
    name: string;
    instructions: string;
    image: string;
    source: string;
    created_at: string;
};
